#ifndef ASYNC_OPERATION_TYPE_H
#define ASYNC_OPERATION_TYPE_H

namespace Crux
{

enum AsyncOperationType
{
	ASYNC_OPERATION_ACCEPT = 1,
	ASYNC_OPERATION_RECV,
	ASYNC_OPERATION_SEND,
	ASYNC_OPERATION_CLOSE,
	ASYNC_OPERATION_ERROR,
	ASYNC_OPERATION_SHUTDOWN,
};

} //namespace Crux

#endif //ASYNC_OPERATION_TYPE_H
